font_family      JetbrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 8.0
force_ltr no

symbol_map U+E0A0-U+E0A3,U+E0C0-U+E0C7 PowerlineSymbols

enable_audio_bell no

background_blur 5

background_opacity 0.5
# Enable vi-mode for copy/paste
copy_on_select no
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

# Vi-style copy mode (enter with `Ctrl+Shift+Space`)
kitty_mod ctrl+shift
map kitty_mod+space toggle_selection
map kitty_mod+h move_backward_word
map kitty_mod+l move_forward_word
map kitty_mod+b move_backward_word
map kitty_mod+w move_forward_word
map kitty_mod+0 move_to_start_of_line
map kitty_mod+$ move_to_end_of_line
map kitty_mod+y copy_to_selection
